swagger: '3.0'
info:
  title: Iberia
  description: >
    This is a demo for a sample REST API.
  version: 1.0.0
schemes:
  - https
host: localhost
basePath: /api
consumes:
  - application/json
produces:
  - application/json

#-----------------------------
paths:
  /person:                # path of the user from your endpoint
    post:                 # endpoint request type (post request)
      tags:               # Tag property
        - Person            # Value of the tag
      summary: creates a new person
      produces:
      - application/json
      parameters:         # request parameters
      - in: body          # request body
        name: sign up     # name of the request, can be any name
        description: It enables a user to create an account
        required: false   # can also be true depending on user preference
        schema:           # Schema definition
          $ref: '#/definitions/signUp' 
      responses:          # server responses
        201:
          description: An object with user details
definitions:        # Schema definition for the request body
  signUp:
    type: object
        properties:
          username:
            type: string
          email:
            type: string
          password:
            type: string