/* eslint-disable linebreak-style */
/* eslint-disable import/extensions */
import Sequelize from 'sequelize';

import sequelize from '../../middleware/sequelize.js';
import LocationModel from '../../models/location.model.js';

const Location = LocationModel(sequelize, Sequelize);

const createLocation = async () => {

  await Location.bulkCreate([
    {
      location_name: 'Lugo',
      location_alt_names: null, 
      location_north: 43.01,
      location_east: -7.54,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Leon',
      location_alt_names: null, 
      location_north: 42.60,
      location_east: -5.57,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Burgos',
      location_alt_names: null, 
      location_north: 42.34,
      location_east: -3.70,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Madrid',
      location_alt_names: null, 
      location_north: 40.42,
      location_east: -3.70,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Barcelona',
      location_alt_names: null, 
      location_north: 41.39,
      location_east: 2.16,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Valencia',
      location_alt_names: null, 
      location_north: 39.47,
      location_east: -3.77,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Zaragoza',
      location_alt_names: null, 
      location_north: 41.66,
      location_east: -0.88,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Malaga',
      location_alt_names: null, 
      location_north: 36.72,
      location_east: -4.42,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Murica',
      location_alt_names: null, 
      location_north: 37.99,
      location_east: -1.13,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Palma',
      location_alt_names: null, 
      location_north: 39.56,
      location_east: 2.65,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Bilbao',
      location_alt_names: null, 
      location_north: 43.26,
      location_east: -2.93,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Sevilla',
      location_alt_names: null, 
      location_north: 37.28,
      location_east: -5.97,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Valladolid',
      location_alt_names: null, 
      location_north: 41.66,
      location_east: -4.72,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Vigo',
      location_alt_names: null, 
      location_north: 42.23,
      location_east: -8.72,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'A Coruna',
      location_alt_names: null, 
      location_north: 43.37,
      location_east: -8.40,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Granada',
      location_alt_names: null, 
      location_north: 37.19,
      location_east: -3.60,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Oviedo',
      location_alt_names: null, 
      location_north: 43.36,
      location_east: -5.84,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Cartagena',
      location_alt_names: null, 
      location_north: 37.61,
      location_east: -0.99,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Pamplona',
      location_alt_names: null, 
      location_north: 42.82,
      location_east: -1.64,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Santander',
      location_alt_names: null, 
      location_north: 43.46,
      location_east: -3.80,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Albacete',
      location_alt_names: null, 
      location_north: 38.99,
      location_east: -1.86,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Alicante',
      location_alt_names: null, 
      location_north: 38.35,
      location_east: -0.48,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Salamanca',
      location_alt_names: null, 
      location_north: 40.97,
      location_east: -5.66,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Logrono',
      location_alt_names: null, 
      location_north: 42.47,
      location_east: -2.45,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Huelva',
      location_alt_names: null, 
      location_north: 37.27,
      location_east: -6.94,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Badajoz',
      location_alt_names: null, 
      location_north: 38.88,
      location_east: -6.97,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Salamanca',
      location_alt_names: null, 
      location_north: 40.43,
      location_east: -3.67,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Girona',
      location_alt_names: null, 
      location_north: 41.98,
      location_east: 2.82,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Gijon',
      location_alt_names: null, 
      location_north: 43.54,
      location_east: -5.66,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Lleida',
      location_alt_names: null, 
      location_north: 41.62,
      location_east: 0.62,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Cadiz',
      location_alt_names: null, 
      location_north: 36.53,
      location_east: -6.29,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Santiago de Compostela',
      location_alt_names: null, 
      location_north: 42.88,
      location_east: -8.54,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Palencia',
      location_alt_names: null, 
      location_north: 42.01,
      location_east: -4.52,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Toledo',
      location_alt_names: null, 
      location_north: 39.86,
      location_east: -4.02,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Ceuta',
      location_alt_names: null, 
      location_north: 35.89,
      location_east: -5.32,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Jaen',
      location_alt_names: null, 
      location_north: 37.77,
      location_east: -3.79,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Algeciras',
      location_alt_names: null, 
      location_north: 36.13,
      location_east: -5.45,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Melilla',
      location_alt_names: null, 
      location_north: 35.29,
      location_east: -2.94,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Almeria',
      location_alt_names: null, 
      location_north: 36.84,
      location_east: -2.46,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Zamora',
      location_alt_names: null, 
      location_north: 41.51,
      location_east: -5.74,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Avila',
      location_alt_names: null, 
      location_north: 40.66,
      location_east: -4.70,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Segovia',
      location_alt_names: null, 
      location_north: 40.95,
      location_east: -4.12,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Cuenca',
      location_alt_names: null, 
      location_north: 40.01,
      location_east: -2.13,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Soria',
      location_alt_names: null, 
      location_north: 41.76,
      location_east: -2.47,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Teruel',
      location_alt_names: null, 
      location_north: 40.35,
      location_east: -1.11,
      population: null,
      location_info: null,
      location_sources: null,
    },

    // Portuguese Cities
    {
      location_name: 'Lisbon',
      location_alt_names: null, 
      location_north: 38.72,
      location_east: -9.13,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Porto',
      location_alt_names: null, 
      location_north: 41.15,
      location_east: -8.61,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Braga',
      location_alt_names: null, 
      location_north: 41.55,
      location_east: -8.42,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Coimbra',
      location_alt_names: null, 
      location_north: 40.20,
      location_east: -8.42,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Evora',
      location_alt_names: null, 
      location_north: 38.57,
      location_east: -7.9,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Faro',
      location_alt_names: null, 
      location_north: 37.02,
      location_east: -7.93,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Aveiro',
      location_alt_names: null, 
      location_north: 40.64,
      location_east: -8.65,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Guarda',
      location_alt_names: null, 
      location_north: 40.54,
      location_east: -7.27,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Santarem',
      location_alt_names: null, 
      location_north: 39.23,
      location_east: -8.68,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Beja',
      location_alt_names: null, 
      location_north: 38.02,
      location_east: -7.86,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Braganca',
      location_alt_names: null, 
      location_north: 41.81,
      location_east: -6.76,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Viseu',
      location_alt_names: null, 
      location_north: 40.66,
      location_east: -7.91,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Maia',
      location_alt_names: null, 
      location_north: 41.24,
      location_east: -8.62,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Sintra',
      location_alt_names: null, 
      location_north: 38.80,
      location_east: -9.38,
      population: null,
      location_info: null,
      location_sources: null,
    },
    {
      location_name: 'Sobral',
      location_alt_names: null, 
      location_north: 39.02,
      location_east: -9.15,
      population: null,
      location_info: null,
      location_sources: null,
    },
  ])
};

const initLocation = async () => {
  sequelize.sync().then(async () => {
    createLocation();
  });
};

export default initLocation;
