definition: 
    openapi: "3.0.0"
    info: 
      title: "IB Swagger Documentation"
      version: process.env.API_VERSION || "undefined"
      description: API Documentation
    tags: tags,
    apis: './*.yaml'