version: '3.8'
services:
  ###############################################################################
  ###                       POSTGRES DB Container                             ###
  ###############################################################################
  db:
    container_name: db
    image: postgres
    build:
      context: .
      target: db
    restart: always
    ports:
      - 6000:6000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    command: ['postgres', '-c', 'logging_collector=on']
