version: "3.8"
services:
  ibe-db:
    image: ibe-db
    container_name: ibe-db
    build:
      context: .
      target: ibe-db
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - 4000:4000
    command: -p 4000 
networks:
  ibe-net:
    driver: "bridge"